// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VrpBackend.EntityFramework;

namespace VrpBackend.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20200120084140_PostGISModels")]
    partial class PostGISModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("VrpBackend.Models.Case", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Point>("Base")
                        .HasColumnType("geometry");

                    b.Property<MultiPoint>("Points")
                        .HasColumnType("geometry");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("VrpBackend.Models.Result", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CaseId")
                        .HasColumnType("bigint");

                    b.Property<double>("CombinedLength")
                        .HasColumnType("double precision");

                    b.Property<double>("ComputationTime")
                        .HasColumnType("double precision");

                    b.Property<double>("LongestRouteLength")
                        .HasColumnType("double precision");

                    b.Property<double>("LongestRouteTime")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberOfRoutes")
                        .HasColumnType("integer");

                    b.Property<MultiLineString>("Routes")
                        .HasColumnType("geometry");

                    b.Property<long>("WorkerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("VrpBackend.Models.Worker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("VrpBackend.Models.Result", b =>
                {
                    b.HasOne("VrpBackend.Models.Case", "Case")
                        .WithMany("Results")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VrpBackend.Models.Worker", "Worker")
                        .WithMany("Results")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
