import {
  WEBSOCKET_BROKEN,
  WEBSOCKET_CLOSED,
  WEBSOCKET_CONNECT,
  WEBSOCKET_DISCONNECT,
  WEBSOCKET_MESSAGE,
  WEBSOCKET_OPEN,
  WEBSOCKET_SEND,
} from '@giantmachines/redux-websocket';

export const DATA_LOADED = "DATA_LOADED";

export const REGISTER_USER = "REGISTER_USER";

export const DATA_REQUESTED = "DATA_REQUESTED";
export const API_ERRORED = "API_ERRORED";

export const ADD_PACKAGE = "ADD_PACKAGE";
export const DELETE_PACKAGE = "DELETE_PACKAGE";
export const EDIT_PACKAGE = "EDIT_PACKAGE";
export const SELECT_PACKAGE = "SELECT_PACKAGE";
export const CENTER_MAP = "CENTER_MAP";
export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
export const TOGGLE_DEPO_MODE = "TOGGLE_DEPO_MODE";
export const ADD_DEPO = "ADD_DEPO";
